/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Elísa' at '26/10/15 19:51' with Gradle 2.8
 *
 * @author Elísa, @date 26/10/15 19:51
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
